import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navebar from "@/components/navbar";
import BreadcrumbsComponent from "@/components/breadcrumbsComp";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navebar/>
        <BreadcrumbsComponent/>
        {children}
        </body>
    </html>
  );
}
